# __Numpy__

In [1]:
# import library = numpy
import numpy as np

### **Creating Numpy Array**

### 1. from Python List

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [ [1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2. Built-in methods arange

In [5]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

### 3. Built-in methods = zeros & ones

In [12]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **Mini Activity**

- **Group 1** : 
- np.linspace, 
- np.eye, 
- arr.shape, 
- arr.reshape

- **Group 2**: 
- np.random.rand, 
- np.random.randn, 
- np.random.randint

- **Group 3**: 
- arr.max, 
- arr.argmax, 
- arr.min, 
- arr.argmin, 
- arr.dtype

### 4. Built-in methods = linspace (jarak antar data bisa diketahui dan sama)

In [4]:
np.linspace(0,1000,25)

array([   0.        ,   41.66666667,   83.33333333,  125.        ,
        166.66666667,  208.33333333,  250.        ,  291.66666667,
        333.33333333,  375.        ,  416.66666667,  458.33333333,
        500.        ,  541.66666667,  583.33333333,  625.        ,
        666.66666667,  708.33333333,  750.        ,  791.66666667,
        833.33333333,  875.        ,  916.66666667,  958.33333333,
       1000.        ])

In [17]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 5. Built-in methods = eye

In [19]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

### 6. Built-in methods = random.rand (membuat array dengan value random, dari 0 - 1)

In [22]:
np.random.rand(10)

array([0.38579053, 0.25346167, 0.95085315, 0.4234065 , 0.46117701,
       0.06088089, 0.06851867, 0.10418387, 0.82662258, 0.50217678])

In [21]:
np.random.rand(5,5)

array([[0.05212364, 0.16371673, 0.41414638, 0.66081012, 0.03063914],
       [0.3579226 , 0.98390376, 0.45501672, 0.82489592, 0.31063679],
       [0.8148137 , 0.61189297, 0.02204332, 0.03698213, 0.46174718],
       [0.62468353, 0.52879223, 0.92692865, 0.66670563, 0.23127808],
       [0.79784511, 0.18377201, 0.39186621, 0.67711799, 0.36691556]])

### 7. Built-in methods = random.randn (membuat array dengan value random dan datanya terdistribusi normal)

In [24]:
np.random.randn(10)

array([-0.30655057,  0.8054681 , -0.22915295, -1.05882059,  0.18652591,
       -1.45832318,  0.3577003 , -1.06250564, -0.57347343,  0.26171212])

In [25]:
np.random.randn(5,5)

array([[ 1.80704584, -0.21517428,  0.12460178,  0.18218355, -0.75286522],
       [ 0.20120582, -1.71500505, -0.05844543,  1.21975602, -0.04625652],
       [-0.23123396, -1.68583161,  1.05982136, -0.56713974,  0.08957129],
       [ 0.23995899,  0.66994548, -0.81131959, -1.59151466, -0.19462066],
       [-0.28901199, -1.13782833, -1.71901222, -0.96100127, -0.38035841]])

### 8. Built-in methods = random.randint (membuat array dengan value random dan datanya berupa integer)

In [29]:
np.random.randint(1,15) #mencari data random dari 1 sampai 15

12

In [6]:
np.random.randint(21,51,10) #mencari data random dari 1 sampai 20 sebanyak 5 data

array([38, 40, 34, 47, 36, 27, 47, 50, 31, 44])

## **Array Attributes**

In [8]:
arr = np.arange(20)
ranarr = np.random.randint(0,50,10)

In [56]:
ranarr

array([31, 20,  9,  5, 16, 18, 37, 20, 34,  1])

In [10]:
# untuk mengubah dimensi
x = arr.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
# mengetahui dimensi
x.shape

(2, 10)

In [59]:
#mencari nilai terbesar dalam array
ranarr.max() 

37

In [60]:
# mencari index nilai terbesar dalam array
ranarr.argmax()

6

In [61]:
#mencari nilai terkecil dalam array
ranarr.min()

1

In [62]:
# mencari index nilai terkecil dalam array
ranarr.argmin()

9

In [63]:
#mengetahui tipe data
arr.dtype

dtype('int32')

# **Indexing** : menampilkan sesuai index tertentu

In [11]:
a = np.arange(11, 21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
# menampilkan index ke-8
a[8]

19

In [15]:
# menampilkan index start: 0, stop: 18, step:2
a[0:18:2]

array([11, 13, 15, 17, 19])

# **Broadcasting**

In [16]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
a[0:4] = 0
a

array([ 0,  0,  0,  0, 15, 16, 17, 18, 19, 20])

# **Slicing**

In [69]:
slice_of_a = a[5:9]
slice_of_a

array([16, 17, 18, 19])

# **Copy**

In [20]:
c = a[5:10].copy()
c

array([16, 17, 18, 19, 20])

# **Indexing 2D Array**

In [21]:
arr_2d = np.array(([5,10,15],[20,25,10],[15,35,25]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 10],
       [15, 35, 25]])

In [82]:
yo= arr_2d[0,1],arr_2d[1,1],arr_2d[2,1]
np.array(yo)

array([10, 25, 35])

In [22]:
arr_2d[1]

array([20, 25, 10])

In [25]:
arr_2d[1][2]

10

In [24]:
arr_2d[1,0]

20

# **2D Array Slicing**

In [36]:
arr_2d[:3, :2]

array([[ 5, 10],
       [20, 25],
       [15, 35]])

In [37]:
arr_2d[2]

array([15, 35, 25])

In [42]:
arr_2d[2, :]

array([15, 35, 25])

# **Lenght of Array**

In [44]:
arr2d = np.zeros((10, 10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
len(arr2d)

10

In [46]:
arr_length = arr2d.shape[0]
arr_length

10

# **Selection**

In [47]:
gaji = np.arange(5, 25)

In [48]:
# selection gaji di atas 10 juta
gaji > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [49]:
bool_gaji = gaji > 10
gaji[bool_gaji]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
gaji[gaji > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
gaji[gaji < 15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# **Aritmetic**

In [75]:
x = np.arange(5, 15)
y = np.arange(15, 25)
y

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
x + x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [76]:
y - x

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [61]:
y / x

array([3.        , 2.66666667, 2.42857143, 2.25      , 2.11111111,
       2.        , 1.90909091, 1.83333333, 1.76923077, 1.71428571])

In [62]:
x * y

array([ 75,  96, 119, 144, 171, 200, 231, 264, 299, 336])

In [64]:
pangkat_dua = x ** 2
pangkat_dua

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196], dtype=int32)

In [65]:
np.sqrt(pangkat_dua)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [66]:
np.exp(x)

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06])

In [67]:
np.max(x)

14

In [68]:
np.sin(x)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [69]:
np.log(x)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])